export default function Head() {
  return (
    <>
      <title>Panaverse by Zahid</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/logo.png" />
    </>
  )
}
// fevicon is the icon on the tab, head.tsx will apply to all pages by default in next js 13. it is for google indexing only